# Generated by Django 5.2.2 on 2025-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_profile_is_employer_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('job_seeker', 'Job Seeker')], default='job_seeker', max_length=20),
        ),
    ]
